# theme = "gruvbox_dark_hard"
# theme = "ayu_dark"
# theme = "sonokai"
theme = "tokyonight"

[editor]
line-number = "relative"
# or ╎
indent-guides = { render = true, character = "┊" }
scrolloff = 0
#default-yank-register = "+" # System clipboard
#	Number of lines to scroll per scroll wheel step
scroll-lines = 2
cursorline = true
# rulers = [120]
# text-width = 120
popup-border = "all"
end-of-line-diagnostics = "hint"
jump-label-alphabet = "asdfjkl;ghqwertuiopnmxcvb"
completion-replace = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# Ignore hidden files?
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
# The minimum severity that a diagnostic must have to be shown inline on the line that contains the primary cursor.
cursor-line = "warning"

[keys.normal]
"{"   = "goto_prev_paragraph"
"}"   = "goto_next_paragraph"
"G"   = "goto_last_line"
"H"   = "goto_window_top"
"L"   = "goto_window_bottom"
"M"   = "goto_window_center"
"0"   = "goto_line_start"
"C-p" = "file_picker_in_current_directory"
"C-k" = ["kill_to_line_end", "insert_at_line_end"]
"D"   = "kill_to_line_end"

[keys.normal."space"]
":"     = "command_palette"
"space" = "file_picker_in_current_directory"

[keys.normal."space".f]
"f" = "file_picker"
"s" = ":write"

[keys.normal.g]
"q" = ":reflow"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"G" = "goto_last_line"
"H" = "goto_window_top"
"L" = "goto_window_bottom"
"M" = "goto_window_center"
"0" = "goto_line_start"

[keys.select.g]
"q" = ":reflow"
