#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Arch Snap 0 (LTS)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux-lts ...'
	linux	/vmlinuz-linux-lts root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/0 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux-lts.img
}
menuentry 'Arch Snap 1 (LTS)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux-lts ...'
	linux	/vmlinuz-linux-lts root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/1 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux-lts.img
}
menuentry 'Arch Snap 2 (LTS)' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux-lts ...'
	linux	/vmlinuz-linux-lts root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/2 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux-lts.img
}


menuentry 'Arch Snap 0' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux ...'
	linux	/vmlinuz-linux root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/0 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux.img
}
menuentry 'Arch Snap 1' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux ...'
	linux	/vmlinuz-linux root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/1 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux.img
}
menuentry 'Arch Snap 2' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-90af650e-8f41-427e-995d-8c08618112dc' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  89f0ca17-e88c-4c20-8a03-02bf73f200b6
	else
	  search --no-floppy --fs-uuid --set=root 89f0ca17-e88c-4c20-8a03-02bf73f200b6
	fi
	echo	'Loading Linux linux ...'
	linux	/vmlinuz-linux root=/dev/mapper/volgr-root rw rootflags=subvol=snaps/2 cryptdevice=UUID=844946c0-3fa9-4cd6-992e-4d53d992f78e:cryptolvm root=/dev/mapper/volgr-root 
	echo	'Loading initial ramdisk ...'
	initrd  /intel-ucode.img /initramfs-linux.img
}
