XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}

CARGO_HOME=${XDG_DATA_HOME}/cargo
DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker
GNUPGHOME=${XDG_DATA_HOME}/gnupg
NODE_REPL_HISTORY=${XDG_STATE_HOME}/node_repl_history
NPM_CONFIG_INIT_MODULE=${XDG_CONFIG_HOME}/npm/config/npm-init.js
NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
PYTHON_HISTORY=${XDG_STATE_HOME}/python_history
REDISCLI_HISTFILE=${XDG_STATE_HOME}/redis/rediscli_history
R_HISTFILE=${XDG_STATE_HOME}/R/history
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
SQLITE_HISTORY=${XDG_CACHE_HOME}/sqlite_history
TEXMFVAR=${XDG_CACHE_HOME}/texlive/texmf-var
ZDOTDIR=${XDG_CONFIG_HOME}/zsh
