#!/bin/sh
# $Id$
# elvis: leo		-- search leo.org
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_dict_languages	"german-english"
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search leo.org
Local options:
  -l=...  languages
Examples:
  $w3_argv0 -l=german-english hello
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-l=*)	setopt	 SURFRAW_dict_languages		$optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
# SURFRAW_quote_ifs=0
w3_parse_args "$@"

if [ -z "$SURFRAW_dict_languages" ]; then
    SURFRAW_dict_languages="german-english"
fi

prefix="https://dict.leo.org/${SURFRAW_dict_languages}/"

if null "$w3_args"; then
    w3_browse_url "https://www.leo.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`

    w3_browse_url "${prefix}${escaped_args}"
fi

