#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  false 
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc rule -a URxvtQuake sticky=on floating=on

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DVI-I-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

pkill -x "panel"
cd ~/.config/bspwm
./panel &
pkill -x "redshift-gtk"
redshift-gtk &
./set_wallpaper.sh &
xrdb ~/.Xresources &
/usr/lib64/gnome-settings-daemon/gnome-settings-daemon &
