#!/bin/bash

FIFO_PATH=/tmp/.sxhkd
SXHKD_PATH=~/.config/sxhkd/sxhkdrc

# TODO remove this later
set -x
exec 1>/tmp/deblog 2>&1

(
    bspc monitor -d 0
    # FIRST_RUN=1
    bspc subscribe monitor_geometry monitor_add | while read -r LINE; do
        MONITOR_ID="$(tr -s ' ' <<< "$LINE" | cut -f2 -d' ')"
        bspc monitor -f "$MONITOR_ID" && bspwm_workspace.sh switch_new
        launch_polybar.sh &
        # if [ "$FIRST_RUN" = 1 ]; then
        #     MONITOR="$(bspc query -M --names -m "$MONITOR_ID")" polybar bspwm &
        #     FIRST_RUN=0
        #  else
        #     MONITOR="$(bspc query -M --names -m "$MONITOR_ID")" polybar bspwm_secondary &
        # fi
    done
) &

# start sxhkd
[ -p /tmp/.sxhkd ] || mkfifo /tmp/.sxhkd
pgrep -x sxhkd || SXHKD_SHELL=bash sxhkd -s /tmp/.sxhkd -t 10 &

find_docstring() {
    MODE=$(grep -FB2 "$1" $SXHKD_PATH | grep -F '# MODE: ' | head -1 | cut -d' ' -f3-)
}

(
    exec 1>/tmp/.sxhkd_modestring 2>/dev/null
    MODE=
    MODE_PREV=
    PREV=

    while read -r LINE; do
        if [[ "$LINE" =~ ^EEnd\ chain ]]; then
            MODE=
        elif [[ "$LINE" =~ ^BBegin\ chain ]]; then
            find_docstring "${PREV#H}"
        elif [[ "$LINE" =~ ^H[^\;]+\;[^\;0-9]+$ ]]; then
            find_docstring "${LINE#H}"
        fi
        if [[ "$MODE" != "$MODE_PREV" ]]; then
            echo "$MODE"
        fi
        PREV=$LINE
        MODE_PREV=$MODE
    done < $FIFO_PATH
) &



# config

bspc config border_width                3
bspc config window_gap                  15
bspc config split_ratio                 0.54
bspc config borderless_monocle          false
bspc config gapless_monocle             false
bspc config paddingless_monocle         false
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false # makes the cursor appear all the time even when unclutter is running
bspc config pointer_modifier            mod4 # super
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config click_to_focus              none
bspc config pointer_follows_monitor     true
bspc config ignore_ewmh_focus           false
bspc config center_pseudo_tiled         true
bspc config honor_size_hints            false
bspc config remove_disabled_monitors    true #?
bspc config remove_unplugged_monitors   true
bspc config directional_focus_tightness low # test
bspc config initial_polarity            first_child


# theme
bspc config presel_feedback_color       \#1d2021 # Color of the node --presel-{dir,ratio} message feedback area.
bspc config normal_border_color         \#665c54 # Color of the border of an unfocused window.
bspc config active_border_color         \#a89984 # Color of the border of a focused window of an unfocused monitor.
bspc config focused_border_color        \#fbf1c7 # Color of the border of a focused window of a focused monitor.


# init

set_wallpaper.sh &

xsetroot -cursor_name left_ptr &

xrdb -merge ~/.Xresources &

# pgrep -x compton || { sleep 0.05; compton; } &
pgrep -x nm-applet || { sleep 0.2; nm-applet; } &
pgrep -x redshift-gtk || { sleep 0.2; redshift-gtk; } &
pgrep -x keynav || { sleep 0.9; keynav; } &
pgrep -x dunst || { sleep 0.1; dunst; } &
pgrep -x xautolock || { sleep 10; xautolock -time 20 -locker "$HOME/.local/share/scripts/exit.sh lock"; } &
pgrep -x udiskie || { sleep 1; udiskie --use-udisks2 --no-automount --tray; } &
pgrep -x unclutter || { sleep 5; unclutter -noevents -root -idle 8; } &

# rules
bspc rule -a scratchpad-terminal sticky=on state=floating hidden=on private=on layer=above
bspc rule -a Zathura state=tiled
bspc rule -a '*:libreoffice' state=tiled
bspc rule -a Emacs state=tiled desktop=e
bspc rule -a mpv state=floating sticky=on locked=on private=on focus=off rectangle=615x350+1285+710 layer=above
