#!/bin/bash

# TODO remove this later
# set -x
# exec 1>/tmp/debllog 2>&1

[ -p /tmp/.sxhkd ] || mkfifo /tmp/.sxhkd
pgrep -x sxhkd || SXHKD_SHELL=bash sxhkd -s /tmp/.sxhkd -t 10 &

bspc monitor -d 0

(
    bspc subscribe monitor | while read -r LINE; do 
    grep '^monitor_geometry' <<< "$LINE" \
        && bspc monitor -f "$(tr s ' ' <<< "$LINE" | cut -f2 -d' ')" \
        && bspwm_workspace.sh switch_new
    done
)&

# config

bspc config border_width              3
bspc config window_gap                21
bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config paddingless_monocle       false
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false # makes the cursor appear all the time even when unclutter is running
bspc config pointer_modifier          mod4 # super
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
bspc config click_to_focus            none
bspc config pointer_follows_monitor   true
bspc config ignore_ewmh_focus         false
bspc config center_pseudo_tiled       true
bspc config honor_size_hints          false
bspc config remove_disabled_monitors  false #?
bspc config remove_unplugged_monitors true
bspc config directional_focus_tightness low # test
bspc config initial_polarity first_child


# init

set_wallpaper.sh &

setxkbmap -option caps:swapescape &

xsetroot -cursor_name left_ptr &

pgrep -x polybar || polybar bspwm &
pgrep -x nm-applet || (sleep 0.1; nm-applet) &
pgrep -x redshift-gtk || (sleep 0.1; redshift-gtk) &
pgrep -x keynav || (sleep 0.9; keynav) &
pgrep -x dunst || dunst &
pgrep -x xautolock || (sleep 10; xautolock -time 10 -locker "$HOME/.local/share/scripts/exit.sh lock") &
pgrep -x udiskie || (sleep 1; udiskie --use-udisks2 --no-automount) &
pgrep -x unclutter || (sleep 5; unclutter -noevents -root -idle 8) &

xrdb -merge ~/.Xresources &



# rules
bspc rule -a scratchpad-terminal sticky=on state=floating hidden=on
bspc rule -a Zathura state=tiled
bspc rule -a '*:libreoffice' state=tiled
bspc rule -a Emacs state=tiled
