#!/bin/sh
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_dict_languages	"ende"
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search dict.cc
Local options:
  -l=...  Two two letter language codes
Examples:
  $w3_argv0 -l=ende hello
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-l=*)	setopt	 SURFRAW_dict_languages		$optarg	;;
	*) return 1 ;;
    esac
    return 0
}

w3_config
# SURFRAW_quote_ifs=0
w3_parse_args "$@"

if [ -z "$SURFRAW_dict_languages" ]; then
    SURFRAW_dict_languages="ende"
fi

prefix="https://${SURFRAW_dict_languages}.dict.cc/?s="

if null "$w3_args"; then
    w3_browse_url "https://${SURFRAW_dict_languages}.dict.cc"
else
    escaped_args=`w3_url_of_arg $w3_args`

    w3_browse_url "${prefix}${escaped_args}"
fi

