#!/bin/sh

. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search jisho.org
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.jisho.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://jisho.org/search?keyword=${escaped_args}"
fi
