#!/bin/sh
# $Id$
# elvis: duden		-- search duden.de/rechtschreibung

. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Open duden.de/rechtschreibung page
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.duden.de/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.duden.de/rechtschreibung/${escaped_args}"
fi
