[manager]
prepend_keymap = [
    # { on = [ "K" ],    run = "seek -5",                           desc = "Seek up 5 units in the preview" },
    # { on = [ "J" ],    run = "seek 5",                            desc = "Seek down 5 units in the preview" },
    { on = [ "i" ],      run = "plugin max-preview",                desc = "Maximize or restore preview" },
    { on = [ "o" ],      run = "plugin open-with-cmd --args=block", desc = "Open with command in the terminal" },
    { on = [ "g", "t" ], run = "cd /tmp",                           desc = "Go to /tmp" },
    { on = [ "g", "l" ], run = "cd ~/load",                         desc = "Go to ~/load" },
    { on = [ "g", "d" ], run = "cd ~/docs",                         desc = "Go to ~/docs" },
    { on = [ "c", "m" ], run = "plugin chmod",                      desc = "chmod selected files" },
    { on = [ "T", "p" ], run = "plugin hide-preview",               desc = "toggle hide preview" },
    { on = [ "l" ],      run = "plugin smart-enter",                desc = "Enter the child directory, or open the file" },
    { on = [ "c", "s" ], run  = "plugin what-size",                 desc = "Calc size of selection or cwd" },
]
