[manager]
prepend_keymap = [
    # { on = [ "K" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    # { on = [ "J" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },
    { on = [ "i" ], run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
    { on = "o", run  = "plugin open-with-cmd --args=block", desc = "Open with command in the terminal" }
]
